'type: documentation':
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'docs/**/*'

'dependencies':
  - changed-files:
      - any-glob-to-any-file:
          - 'package.json'
          - 'package-lock.json'

'platform: electron':
  - changed-files:
      - any-glob-to-any-file:
          - 'electron/**/*'

'frontend':
  - changed-files:
      - any-glob-to-any-file:
          - 'src/**/*.html'
          - 'src/**/*.css'
          - 'src/**/*.js'

'build':
  - changed-files:
      - any-glob-to-any-file:
          - 'vite.config.js'
          - '.github/workflows/**'
